namespace EShop.Catalog.Products.Dtos;

/// <summary>
/// Data Transfer Object (DTO) representing a product in the catalog.
/// Used to transfer product data between client and server or application layers.
/// </summary>
public record ProductDto
{
    /// <summary>
    /// Gets the unique identifier of the product.
    /// This value is typically generated by the system and should not be modified.
    /// </summary>
    public Guid Id { get; init; }

    /// <summary>
    /// Gets the name of the product.
    /// This value is required and should be a user-friendly product name.
    /// </summary>
    public string Name { get; init; } = null!;

    /// <summary>
    /// Gets the list of categories the product belongs to.
    /// Provides detailed information to help users understand the product.
    /// </summary>
    public string Description { get; init; } = null!;

    /// <summary>
    /// Gets the file path or URL of the product's image.
    /// This is used for displaying the product visually in the UI.
    /// </summary>
    public string ImageFile { get; init; } = null!;

    /// <summary>
    /// Gets the price of the product.
    /// Must be a non-negative decimal value representing the product's cost.
    /// </summary>
    public decimal Price { get; init; }

    /// <summary>
    /// Gets the category under which the product is listed.
    /// This helps organize products and enable category-based filtering.
    /// </summary>
    public List<string> Category { get; init; } = [];
}
