services:
    eshop_db:
        container_name: eshop_db
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - postgres_eshop_db:/var/lib/postgres/data/
    seq:
        container_name: seq
        environment:
            - ACCEPT_EULA=Y
        restart: always
        ports:
            - "5341:5341"
            - "9091:80"