services:
    eshop_db:
        container_name: eshop_db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=eshop_db
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - postgres_eshop_db:/var/lib/postgres/data/
     